### Spawning a new worker
POST http://localhost:8080
###


@workerId = 0c5c5dfb-6337-4e76-82d5-7697a4025eef

### Listing workers
GET http://192.168.50.13:8080/workers

### Get worker info {{workerId}}
GET http://localhost:8080/worker/{{workerId}}

### Stop a worker
DELETE http://localhost:8080/worker/{{workerId}}