### Spawning a new worker
POST http://localhost:8080
###


@workerId = b067ea03-f648-4832-9741-08140debc31a

### Listing workers
GET http://localhost:8080/workers

### Get worker info {{workerId}}
GET http://localhost:8080/worker/{{workerId}}

### Stop a worker
DELETE http://localhost:8080/worker/{{workerId}}